version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: portal/nginx:latest
    volumes:
      - ./ng-app/dist/portal/:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    restart: always
    depends_on:
      - python-service
      - node-service
      - reverseproxy
    container_name: ng-app

  node-service:
    build:
      context: .
      dockerfile: Dockerfile.node-service
    command: ["npm", "run", "start-be"]
    image: portal/node-service:latest
    volumes:
      - ./node-service/src:/root/node-service/src
    ports:
      - 8080
    restart: always
    depends_on:
      - mongo
      - reverseproxy
    container_name: node-service

  python-service:
    build:
      context: .
      dockerfile: Dockerfile.python-service
    image: portal/python-service:latest
    volumes:
      - ./python-service:/root/python-service
    ports:
      - 5000
    depends_on:
      - reverseproxy
    restart: always
    container_name: python-service

  mongo:
    image: webhippie/mongodb:latest
    volumes:
      - ./mongodb/db:/data/db/
    ports:
      - 27017
    restart: always
    container_name: mongo

  reverseproxy:
    build:
      context: .
      dockerfile: Dockerfile.reverseproxy
    image: portal/nginx:latest
    volumes:
      - ./nginx.reverseproxy.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
      - 5000:5000
    restart: always
    container_name: reverseproxy
