version: '3.3'

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    command: ['nginx', '-g', 'daemon off;']
    image: nginx:latest
    expose:
      - '80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: always
    depends_on:
      - web
      - api
      - rest
    container_name: proxy

  sonarqube:
    build:
      context: .
      dockerfile: Dockerfile.sonarqube
    ports:
      - 9000:9000
      - 9092:9092
    volumes:
      - $PWD/sonar:/opt/sonarqube/data
    restart: always
    container_name: sonarqube

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: ['npm', 'run', 'docker-start']
    image: portal/web:latest
    volumes:
      - ./:/root/portal
      - /root/portal/node_modules
    ports:
      - 4200:4200
      - 9876:9876
    environment:
      - DISPLAY=:99
      - CHROME_BIN=chromium
    restart: always
    container_name: web

  rest:
    build:
      context: .
      dockerfile: Dockerfile.rest
    command: ['npm', 'run', 'start-be-debug']
    image: portal/rest:latest
    volumes:
      - ./:/root/portal
      - /root/portal/node_modules
    ports:
      - 8080:8080
      - 9229:9299
    restart: always
    depends_on:
      - mongo
      - api
      - web
      - sonarqube
    container_name: rest

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: portal/api:latest
    volumes:
      - ./:/root/portal
    ports:
      - 5000:5000
    restart: always
    container_name: api

  mongo:
    image: mongo:latest
    volumes:
      - ./mongodb/db:/data/db/
    expose:
      - '27017'
    ports:
      - 27017:27017
    restart: always
    container_name: mongo
