FROM node:current-slim

LABEL Joshua S. Eagle

WORKDIR /root/

COPY ./node-service /root/node-service/

WORKDIR /root/node-service/

RUN apt-get update && apt-get install -y build-essential python

RUN npm install -g nodemon

RUN npm install --silent

EXPOSE 8080

CMD ["npm", "run", "start"]
