FROM node

LABEL firstname lastname

WORKDIR /root/

COPY ./ng-app /root/ng-app

WORKDIR /root/ng-app

RUN npm i -g @angular/cli && npm i

# Install Chrome
RUN apt-get update && apt-get install -y --no-install-recommends chromium iceweasel && apt-get clean

CMD ["npm", "run", "test-coverage"]
