FROM node

MAINTAINER Joshua Eagle

WORKDIR /root/

# Update NPM
RUN npm cache clean -f

COPY . /root/portal

WORKDIR /root/portal

RUN npm install -g @angular/cli

RUN npm install --silent

# Install Chrome
# RUN apt-get update && apt-get install -y --no-install-recommends chromium iceweasel && apt-get clean

ENV API_HOST api

EXPOSE 4200

CMD ["npm", "run", "docker-start"]
