FROM node

MAINTAINER Joshua Eagle

WORKDIR /root/

# Update NPM
RUN npm cache clean -f

COPY . /root/portal

WORKDIR /root/portal/service/

RUN npm install -g nodemon

RUN npm install --silent

EXPOSE 8080

CMD ["npm", "run", "start-be"]
