version: '3.3'

services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    command: ["nginx", "-g", "daemon off;"]
    image: nginx:latest
    expose:
      - '80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: always
    depends_on:
      - web
      - api
      - rest

  sonarqube:
    build:
      context: .
      dockerfile: Dockerfile.sonarqube
    ports:
      - 9000:9000
      - 9092:9092
    volumes:
      - $PWD/sonar:/opt/sonarqube/data
    restart: always
    depends_on:
      - web
      - api
      - rest

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: ["ng", "serve", "--host", "0.0.0.0"]
    image: portal/web:latest
    volumes:
      - ./:/root/portal
      - /root/portal/node_modules
    ports:
      - 4200:4200
    restart: always

  rest:
    image: portal/rest:latest
    volumes:
      - ./:/root/portal
      - node_modules:/root/portal/node_modules
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mongo

  api:
    image: portal/api:latest
    volumes:
      - ./:/root/portal
    restart: always
    depends_on:
      - rest

  mongo:
    image: mongo:latest
    volumes:
      - ./mongodb/db:/data/db/
    expose:
      - '27017'
    ports:
      - 27017:27017
    restart: always

volumes:
  node_modules:
