version: '3.3'

services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    command: ["nginx", "-g", "daemon off;"]
    image: nginx:latest
    expose:
      - '80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: always
    depends_on:
      - web
      - api
      - rest

  sonarqube:
    build:
      context: .
      dockerfile: Dockerfile.sonarqube
    ports:
      - 9000:9000
      - 9092:9092
    volumes:
      - $PWD/sonar:/opt/sonarqube/data
    restart: always
    depends_on:
      - web
      - api
      - rest

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: ["ng", "serve", "--host", "0.0.0.0", "--disable-host-check"]
    image: portal/web:latest
    volumes:
      - ./:/root/portal
      - /root/portal/node_modules
    ports:
      - 4200:4200
      - 9876:9876
    environment:
      - DISPLAY=:99
      - CHROME_BIN=chromium
    restart: always

  rest:
    build:
      context: .
      dockerfile: Dockerfile.rest
    command: ["npm", "run", "start-be-debug"]
    image: portal/rest:latest
    volumes:
      - ./:/root/portal
      - /root/portal/node_modules
    ports:
      - 8080:8080
      - 9229:9299
    restart: always
    depends_on:
      - mongo

  api:
    build:
        context: .
        dockerfile: Dockerfile.api
    image: portal/api:latest
    volumes:
        - ./:/root/portal
    ports:
        - 5000:5000
    restart: always
    depends_on:
        - rest

  mongo:
    image: mongo:latest
    volumes:
      - ./mongodb/db:/data/db/
    expose:
      - '27017'
    ports:
      - 27017:27017
    restart: always
