FROM python

MAINTAINER Joshua S. Eagle

WORKDIR /root/

COPY . /root/portal/

WORKDIR /root/portal/

RUN pip install -r requirements.txt

WORKDIR /root/portal/python-service

EXPOSE 5000

CMD ["python", "app.py"]
