FROM arm32v7/python:latest

LABEL Joshua S. Eagle

WORKDIR /root/

COPY ./python-service/ /root/python-service/

WORKDIR /root/python-service/

RUN pip install -r flask RPi.gpio

EXPOSE 5000

CMD ["python", "app.py"]
