FROM node:latest

MAINTAINER Joshua Eagle

WORKDIR /root/

# Update NPM
RUN npm cache clean -f

COPY . /root/portal

WORKDIR /root/portal

RUN npm install -g @angular/cli

RUN npm install --silent

# Install Chrome
# RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
# RUN dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install
RUN apt-get update \
    && apt-get install -y --no-install-recommends chromium

ENV API_HOST api

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0"]
