FROM node:latest

MAINTAINER Joshua Eagle

WORKDIR /root/

COPY . /root/portal

WORKDIR /root/portal/

RUN npm install --silent

RUN npm install -g nodemon --silent

EXPOSE 8080

CMD ["npm", "run", "start-be"]
