FROM node:latest

MAINTAINER Joshua Eagle

WORKDIR /root/

# Update NPM
RUN npm cache clean -f

COPY . /root/portal

WORKDIR /root/portal

RUN npm install -g @angular/cli

RUN npm install --silent

ENV API_HOST api

EXPOSE 80

CMD ["ng", "serve"]
