version: '3.3'

services:
  web:
    image: gate-keeper/web:latest
    volumes:
      - ./:/root/gate-keeper
      - /root/gate-keeper/node_modules
      - node_modules:/root/gate-keeper/node_modules
    ports:
      - 80:80
    restart: always

  rest:
    image: gate-keeper/rest:latest
    volumes:
      - ./:/root/gate-keeper
      - node_modules:/root/gate-keeper/node_modules
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mongo

  api:
    image: gate-keeper/api:latest
    volumes:
      - ./:/root/gate-keeper
    restart: always
    depends_on:
      - rest

  mongo:
    image: mongo:latest
    volumes:
      - ./mongodb/db:/data/db/
    expose:
      - '27017'
    ports:
      - 27017:27017
    restart: always

volumes:
  node_modules: