FROM python

MAINTAINER Joshua S. Eagle

WORKDIR /root/

COPY ./python-service/ /root/python-service/

WORKDIR /root/python-service/

RUN pip install -r requirements.txt

WORKDIR /root/portal/python-service

EXPOSE 5000

CMD ["python", "app.py"]
